config/routes.rb
Rails.application.routes.draw do
  # #エンドユーザー
  #  root to: 'end_users#top'
  #  get 'end_users/my_page', to: 'end_users#show'
  #  get 'end_users/edit', to: 'end_users#edit'
  #  patch 'end_users/edit', to: 'end_users#update'
  #  get 'end_users/unsubscribe', to: 'end_users#unsubscribe'
  #  patch 'end_users/withdraw', to: 'end_users#withdraw'
  #  #商品end_user
  #  get '/items', to: 'items#index'
  #  get '/items/:id', to: 'items#show', as: 'item'
  #  #カート内商品end_user
  #  get '/cart_items', to: 'cart_items#index'
  #  patch '/cart_items/:id', to: 'cart_items#update'
  #  delete '/cart_items/:id', to: 'cart_items#destroy'
  #  delete '/cart_items/:destroy_all', to: 'cart_items#destroy_all'
  #  post '/cart_items', to: 'cart_items#create'


   
  #  #管理者
  #  get 'admin/', to: 'admins#top'
  #  get 'admin/end_users', to: 'admins#index'
  #  #商品admin
  #  get 'admin/items', to: 'admin_items#index'
  #  get 'admin/items/new', to: 'admin_items#new'
  #  post 'admin/items/new', to: 'admin_items#create'
  #  get 'admin/items/:id', to: 'admin_items#show', as: 'admin_item'
  #  #ジャンル
  #  get 'admin/genres', to: 'genres#index'
  #  post 'admin/genres', to:'genres#create'
  #  get 'admin/genres/:id/edit', to: 'genres#edit', as:'admin_edit_genres'
  #  patch 'admin/genres/:id/edit', to: 'genres#update', as:'admin_update_genres'
  #  put 'admin/genres/:id/edit', to: 'genres#update'



  # namespace :public do 
  #   resources :items, only: [:index,:new,:create,:show,:edit,:update], path:'/'
  #   resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create], path:'/'
  #   resources :end_users, only: [:show,:edit,:update,:unsubscribe,:withdraw], path: 'end_users'
  # end

  scope module: 'public' do
    root to: 'items#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create]
    get 'cart_items/destroy_all', to: 'cart_items#destroy_all',as: 'cart_items_destroy_all'
    get 'end_users/my_page', to: 'end_users#show'
    get 'end_users/edit', to: 'end_users#edit'
    patch 'end_users/edit', to: 'end_users#update'
    get 'end_users/unsubscribe', to: 'end_users#unsubscribe'
    patch 'end_users/withdraw', to: 'end_users#withdraw'
    
    post 'orders/confirm', to: 'orders#confirm',as: 'confirm'
    get 'orders/complete', to: 'orders#complete'
    resources :orders, only: [:index,:show,:create,:new]

    resources :addresses, only: [:index,:create,:edit,:update,:destroy]
  end
  namespace :admin do 
    root to: 'top#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update] do
      collection do 
        get 'search'
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    patch 'genres/:id/edit', to: 'genres#update'
    resources :end_users, only: [:index]
    resources :orders, only: [:index,:show,:update]
    resources :order_details, only: [:update]
  end




  devise_for :admin, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :order_details
    has_many :cart_items
    attachment :image
    validates :without_tax, numericality: true

    def self.search(search)
        if search
          where('name LIKE(?)', "%#{search}%")
        else
          all
        end
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
        @items = Item.all
        @items = Item.search(params[:name])
    end

    def new
        @item = Item.new
        @items = Item.search(params[:name])
    end

    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to admin_item_path(@item.id)
        else
            render :new
        end
    end

    def show
        @item = Item.find(params[:id])
        @items = Item.search(params[:name])
    end

    private
    def item_params
        params.require(:item).permit(:name,:genre_id,:description,:without_tax, :image, :is_sold)
    end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_search.html.erb
<%
=begin%>
 <%= form_with(url: admin_items_path, local: true, method: :get) do |f| %>
  <%= f.text_field :name, placeholder: "投稿を検索する" %>
  <%= f.submit "検索" %>
<% end %> 
<%
=end%>

<%= form_tag(admin_items_path, :method => "get") do %>
    <%= text_field_tag :name, '', placeholder:"Search"%>  
    <%= button_tag sanitize('<i class="fa fa-search"></i>'), :type => "submit",
    :class =>"btn btn-default btn-s-md" %> 
<% end %> 

app/views/admin/items/index.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-md-6 offset-md-2">
            
            <%= render "admin/items/search", items:@items %>
            <table>
                <tr>
                <th>商品ID</th>
                <th>商品名</th>
                <th>税抜価格</th>
                <th>ジャンル</th>
                <th>ステータス</th>
                </tr>
                <% @items.each do |f| %>
                <tr>
                <td><%= f.id %></td>
                <td>
                <%= link_to admin_item_path(f.id) do %>
                    <%= f.name %>
                <% end %>
                </td>
                <td><%= f.without_tax %></td>
                <td><%= f.genre.genre_name %></td>
                <td>
                    <% if f.is_sold == false %>
                        <p>販売中</p>
                    <% else %>
                        <p>売り切れ</p>
                    <% end %>
                </td>
                </tr>
                <% end %>
            </table>

            <%= link_to '商品新規登録',  new_admin_item_path %>
        </div>
    </div>
</div>

app/views/admin/items/new.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-md-6 offset-md-2">
            <%= render "admin/items/search", items:@items %>
            <%= form_for @item, url: admin_items_path do |i| %>
                <%= i.attachment_field :image %>   
                    <table>
                        <tr>
                            <td>
                            商品
                            </td>
                            <td>
                            <%= i.text_field :name %>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            商品説明
                            </td>
                            <td>
                            <%= i.text_area :description %>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            ジャンル
                            </td>
                            <td>
                            <%= i.collection_select :genre_id, Genre.all, :id, :genre_name, include_blank: "選択して下さい" %> 
                            </td>
                        </tr>
                        <tr>
                            <td>
                            税抜価格
                            </td>
                            <td>
                            <%= i.text_field :without_tax %>
                            </td>
                        </tr>
                        <tr>
                            <td>
                            販売ステータス
                            </td>
                            <td>
                            <%= i.select :is_sold, [["販売中", "false"], ["売り切れ", "true"]], include_blank: "選択して下さい"  %>
                            </td>
                        </tr>
                    </table>
                <%= i.submit '新規登録'%>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container">
    <div class = "row">
        <div class = "col-md-6 offset-md-2">
            <%= render "admin/items/search", items:@items %>
            <%= attachment_image_tag @item, :image %>
            <table>
                <tr>
                    <td>商品</td>
                    <td><%= @item.name %></td>
                </tr>
                <tr>
                    <td>商品説明</td>
                    <td><%= @item.description %></td>
                </tr>
                <tr>
                    <td>ジャンル</td>
                    <td><%= @item.genre.genre_name %></td>
                </tr>
                <tr>
                    <td>税抜価格</td>
                    <td><%= @item.without_tax %></td>
                </tr>
                <tr>
                    <td>販売ステータス</td>
                    <td>
                    <% if @item.is_sold == false %>
                        <p>販売中</p>
                    <% else %>
                        <p>売り切れ</p>
                    <% end %>
                </td>
                </tr>
            </table>
        </div>
    </div>
</div>