config/routes.rb
Rails.application.routes.draw do
  # #エンドユーザー
  #  root to: 'end_users#top'
  #  get 'end_users/my_page', to: 'end_users#show'
  #  get 'end_users/edit', to: 'end_users#edit'
  #  patch 'end_users/edit', to: 'end_users#update'
  #  get 'end_users/unsubscribe', to: 'end_users#unsubscribe'
  #  patch 'end_users/withdraw', to: 'end_users#withdraw'
  #  #商品end_user
  #  get '/items', to: 'items#index'
  #  get '/items/:id', to: 'items#show', as: 'item'
  #  #カート内商品end_user
  #  get '/cart_items', to: 'cart_items#index'
  #  patch '/cart_items/:id', to: 'cart_items#update'
  #  delete '/cart_items/:id', to: 'cart_items#destroy'
  #  delete '/cart_items/:destroy_all', to: 'cart_items#destroy_all'
  #  post '/cart_items', to: 'cart_items#create'


   
  #  #管理者
  #  get 'admin/', to: 'admins#top'
  #  get 'admin/end_users', to: 'admins#index'
  #  #商品admin
  #  get 'admin/items', to: 'admin_items#index'
  #  get 'admin/items/new', to: 'admin_items#new'
  #  post 'admin/items/new', to: 'admin_items#create'
  #  get 'admin/items/:id', to: 'admin_items#show', as: 'admin_item'
  #  #ジャンル
  #  get 'admin/genres', to: 'genres#index'
  #  post 'admin/genres', to:'genres#create'
  #  get 'admin/genres/:id/edit', to: 'genres#edit', as:'admin_edit_genres'
  #  patch 'admin/genres/:id/edit', to: 'genres#update', as:'admin_update_genres'
  #  put 'admin/genres/:id/edit', to: 'genres#update'



  # namespace :public do 
  #   resources :items, only: [:index,:new,:create,:show,:edit,:update], path:'/'
  #   resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create], path:'/'
  #   resources :end_users, only: [:show,:edit,:update,:unsubscribe,:withdraw], path: 'end_users'
  # end

  scope module: 'public' do
    root to: 'items#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create]
    get 'cart_items/destroy_all', to: 'cart_items#destroy_all',as: 'cart_items_destroy_all'
    get 'end_users/my_page', to: 'end_users#show'
    get 'end_users/edit', to: 'end_users#edit'
    patch 'end_users/edit', to: 'end_users#update'
    get 'end_users/unsubscribe', to: 'end_users#unsubscribe'
    patch 'end_users/withdraw', to: 'end_users#withdraw'
    
    post 'orders/confirm', to: 'orders#confirm',as: 'confirm'
    get 'orders/complete', to: 'orders#complete'
    resources :orders, only: [:index,:show,:create,:new]

    resources :addresses, only: [:index,:create,:edit,:update,:destroy]
  end
  namespace :admin do 
    root to: 'top#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update] do
      collection do 
        get 'search'
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    patch 'genres/:id/edit', to: 'genres#update'
    resources :end_users, only: [:index]
    resources :orders, only: [:index,:show,:update]
    resources :order_details, only: [:update]
  end




  devise_for :admin, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    def index
        @genres = Genre.all
        @genre = Genre.new
        @items = Item.search(params[:name])
    end

    def create
        @items = Item.search(params[:name])
        @genres = Genre.all
        @genre = Genre.new(genre_params)
        if @genre.save
            redirect_to admin_genres_path
        else
           render :index
        end
    end

    def edit
        @items = Item.search(params[:name])
        @genre = Genre.find(params[:id])
    end

    def update
        @items = Item.search(params[:name])
        @genre = Genre.find(params[:id])
        @genres= Genre.all
        if @genre.update(genre_params)
            redirect_to admin_genres_path
        else
           render :edit
        end
    end

    private
    def genre_params
        params.require(:genre).permit(:genre_name,:is_effective)
    end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<%= render "admin/items/search", items:@items %>
<%= form_for @genre, url: edit_admin_genre_path(@genre.id) do |f| %>
    <table>
        <td>
        ジャンル
        <%= f.text_field :genre_name %>
        有効
        <%= f.radio_button :is_effective, :ture %>
        無効
        <%= f.radio_button :is_effective, :false %>
        <%= f.submit '変更を保存する' %>
        </td>
    </table>
<% end %>

app/views/admin/genres/index.html.erb
<%= render "admin/items/search", items:@items %>

<h1>ジャンル一覧・追加</h1>

<%= form_for @genre, url: admin_genres_path do |f| %>
    
    <table>
        <td>
        ジャンル
        <%= f.text_field :genre_name %>
        有効
        <%= f.radio_button :is_effective, :ture %>
        無効
        <%= f.radio_button :is_effective, :false %>
        <%= f.submit '追加'%>
        </td>
    </table>
<% end %>

<table>
    <tr>
        <th >ジャンル</th>
        <th >状態</th>
        <th ></th>
    <% @genres.each do |genre| %>
    <tr>
        <td>
            <%= genre.genre_name%>
        </td>
        <% if genre.is_effective == false%>
        <td>
            無効
        </td>
        <% else %>
        <td>
            有効
        </td>
        <% end %>
        <td>
        <%= link_to "編集する", edit_admin_genre_path(genre.id)%>
        </td>
</tr>
    <% end %> 

</table>