config/routes.rb
Rails.application.routes.draw do
  # #エンドユーザー
  #  root to: 'end_users#top'
  #  get 'end_users/my_page', to: 'end_users#show'
  #  get 'end_users/edit', to: 'end_users#edit'
  #  patch 'end_users/edit', to: 'end_users#update'
  #  get 'end_users/unsubscribe', to: 'end_users#unsubscribe'
  #  patch 'end_users/withdraw', to: 'end_users#withdraw'
  #  #商品end_user
  #  get '/items', to: 'items#index'
  #  get '/items/:id', to: 'items#show', as: 'item'
  #  #カート内商品end_user
  #  get '/cart_items', to: 'cart_items#index'
  #  patch '/cart_items/:id', to: 'cart_items#update'
  #  delete '/cart_items/:id', to: 'cart_items#destroy'
  #  delete '/cart_items/:destroy_all', to: 'cart_items#destroy_all'
  #  post '/cart_items', to: 'cart_items#create'


   
  #  #管理者
  #  get 'admin/', to: 'admins#top'
  #  get 'admin/end_users', to: 'admins#index'
  #  #商品admin
  #  get 'admin/items', to: 'admin_items#index'
  #  get 'admin/items/new', to: 'admin_items#new'
  #  post 'admin/items/new', to: 'admin_items#create'
  #  get 'admin/items/:id', to: 'admin_items#show', as: 'admin_item'
  #  #ジャンル
  #  get 'admin/genres', to: 'genres#index'
  #  post 'admin/genres', to:'genres#create'
  #  get 'admin/genres/:id/edit', to: 'genres#edit', as:'admin_edit_genres'
  #  patch 'admin/genres/:id/edit', to: 'genres#update', as:'admin_update_genres'
  #  put 'admin/genres/:id/edit', to: 'genres#update'



  # namespace :public do 
  #   resources :items, only: [:index,:new,:create,:show,:edit,:update], path:'/'
  #   resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create], path:'/'
  #   resources :end_users, only: [:show,:edit,:update,:unsubscribe,:withdraw], path: 'end_users'
  # end

  scope module: 'public' do
    root to: 'items#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
    resources :cart_items, only: [:index,:update,:destroy,:destroy_all,:create]
    get 'cart_items/destroy_all', to: 'cart_items#destroy_all',as: 'cart_items_destroy_all'
    get 'end_users/my_page', to: 'end_users#show'
    get 'end_users/edit', to: 'end_users#edit'
    patch 'end_users/edit', to: 'end_users#update'
    get 'end_users/unsubscribe', to: 'end_users#unsubscribe'
    patch 'end_users/withdraw', to: 'end_users#withdraw'
    
    post 'orders/confirm', to: 'orders#confirm',as: 'confirm'
    get 'orders/complete', to: 'orders#complete'
    resources :orders, only: [:index,:show,:create,:new]

    resources :addresses, only: [:index,:create,:edit,:update,:destroy]
  end
  namespace :admin do 
    root to: 'top#top'
    resources :items, only: [:index,:new,:create,:show,:edit,:update] do
      collection do 
        get 'search'
      end
    end
    resources :genres, only: [:index,:create,:edit,:update]
    patch 'genres/:id/edit', to: 'genres#update'
    resources :end_users, only: [:index]
    resources :orders, only: [:index,:show,:update]
    resources :order_details, only: [:update]
  end




  devise_for :admin, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :end_users, controllers: {
    sessions:      'end_users/sessions',
    passwords:     'end_users/passwords',
    registrations: 'end_users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<header>
  <h1 class="logo">NaganoCake</h1>
  <nav class="shop-nav">
    <ul class="nav navbar-nav navbar-right">
    <% if end_user_signed_in? %>
      <li >
        <%= link_to "ロゴ", root_path,class: "header-item"%>
      </li>
      <li >
        <%= link_to "マイページ", end_users_my_page_path,class: "header-item" %>
      </li>
      <li >
        <%= link_to "商品一覧", items_path,class: "header-item" %>
      </li>
      <li >
        <%= link_to "カート", cart_items_path ,class: "header-item"%>
      </li>
      <li >
        <%= link_to "ログアウト",destroy_end_user_session_path, method: :delete,class: "header-item" %>
      </li>
    <% elsif admin_signed_in? %>
      <li >
        <%= link_to "ロゴ",  root_path,class: "header-item"%>
      </li>
      <li >

        <%= link_to "商品一覧",admin_items_path ,class: "header-item"%>
      </li>
      <li >
        <%= link_to '会員一覧',admin_end_users_path,class: "header-item" %>
      </li>
      <li >
      <%= link_to '注文履歴一覧',admin_orders_path ,class: "header-item"%>
      </li>
      <li >
        <%= link_to "ジャンル一覧", admin_genres_path ,class: "header-item"%>
      </li>
      <li >
        <%= link_to "ログアウト",destroy_admin_session_path, method: :delete,class: "header-item" %>
      </li>
    <% else %>
      <li >
        <%= link_to "ロゴ", root_path ,class: "header-item"%>
      </li>
      <li >
        <%= link_to "商品一覧", items_path,class: "header-item" %>
      </li>
      <li >
        <%= link_to "新規登録", new_end_user_registration_path ,class: "header-item"%>
      </li>
      <li >
        <%= link_to "ログイン",new_end_user_session_path,class: "header-item" %>
      </li>
    <% end %>
    </ul>
  </nav>
</header>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>